---
vms:
- name: master
  box: centos-65-x64-virtualbox-nocm
  roles:
  - pe-puppet-master
- name: agent
  hostname: agent.local
  box: centos-65-x64-virtualbox-nocm
  roles:
  - pe-puppet-agent
# - name: ubuntu
#   hostname: ubuntu.local
#   box: ubuntu-server-12042-x64-vbox4210-nocm
#   roles:
#   - network-only